kind: Pod
apiVersion: v1
metadata:
  name: alpine
spec:
  containers:
  - name: apline
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: ssd-disk
