apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda
  namespace: redpanda
spec:
  interval: 5m
  chart:
    spec:
      chart: redpanda
      version: "5.6.*"
      sourceRef:
        kind: HelmRepository
        name: redpanda
        namespace: redpanda
      interval: 1m
  values:
    namespace: redpanda
