apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-helm-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: aws-cluster-config
      namespace: crossplane-system
      key: kubeconfig
